### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by Akurosia** [Rawrington/SkillDisplay#10]
When i try to build, i get following error

```
# npm run build

> skilldisplay@0.3.0 build /SkillDisplay
> react-scripts build

Creating an optimized production build...
Failed to compile.

./src/App.js
Cannot find file './Rotation' in './src'.

```
How can i fix this?

**Comment by Rawrington** [comment]
hi sorry, I forgot to upload a source file, I've been really distracted with real life issues as of late I'll be committing an update soon

**Comment by Rawrington** [comment]
I have included the missing files, sorry for the inconvenience, I am currently working on OverlayPlugin support which doesn't quite work yet I'll be fixing it soon.
