### ISSUE TITLE
Default WSServer URLs don't work

### ISSUE THREAD

**Issue by quisquous** [Rawrington/SkillDisplay#49]
OverlayPlugin's WSServer urls look like this, when you generate them from the OverlayPlugin WSServer tab: `https://rawrington.github.io/SkillDisplay/?HOST_PORT=wss://127.0.0.1:10501`

Without a slash at the end, [this code](https://github.com/Rawrington/SkillDisplay/blob/c1dda4bacca2a9525767dc8df411cc7b95d3be96/src/ACTListener.js#L10) generates the wrong wsUri.

I think this code should add in a trailing slash if it doesn't exist.

**Comment by Rawrington** [comment]
Should be addressed in the latest commit!
