### ISSUE TITLE
Invalid Action IDs

### ISSUE THREAD

**Issue by ayyaruq** [Rawrington/SkillDisplay#52]
The xivapi service is getting spammed by invalid action IDs, for example `/Action/218103995`. Can some validation be added to this? There's fixed range bounds for different actions, for example standard combat actions go from 1-20,000, while crafting actions have a prefix of 100k and cover 100,001-100,300.

**Comment by Rawrington** [comment]
I'm merging in the bandwith changes today and I'll be addressing this later, I'll just add some quick sanity checks

**Comment by Rawrington** [comment]
Should be addressed in the latest commit!
