### ISSUE TITLE
Auto attack not being hidden on timeline

### ISSUE THREAD

**Issue by MyTechnoHunter** [Rawrington/SkillDisplay#54]
seems the recent fix for bandwidth that got merged has made it not hide the auto attack actionID from the timeline..

**Comment by Rawrington** [comment]
on it, I'll fix it later today!

**Comment by tancred423** [comment]
[I still encounter this issue.](https://tanc.red/share/2021_01_20_I00gsJs6w9.png)
The screenshot was made with Astrologian auto attacks in Mist on a Striking Dummy.

**Comment by Rawrington** [comment]
Should be fixed now, I fixed the conditions finally oops
